import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/app/component/Navbar/navbar";
import Link from "next/link"
import Footer from "../app/component/Footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

      <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
